### ISSUE TITLE
Update json schema to validate new alexa reports

### ISSUE THREAD

**Issue by Agilulfo** [alexa-samples/alexa-smarthome#100]
The following Alexa events are not validated by the provided json schema:
https://developer.amazon.com/docs/device-apis/alexa-discovery.html#addorupdatereport
https://developer.amazon.com/docs/device-apis/alexa-discovery.html#deletereport

**Comment by nathanguk** [comment]
I think I'm having the same issue when using the schema described in both the addOrDeleteReport or deleteReport documentation, the Alexa events api endpoint returns the following error     

"payload": {
        "code": "INVALID_REQUEST_EXCEPTION",
        "description": "Event or endpoint is missing in the resquest."
}

**Comment by mnathsandeep** [comment]
Hi did you find solution for this, iam using the latest schema (http://json-schema.org/draft-06/schema#) but still problem exists

**Comment by dievaa** [comment]
I tested the schema from the documentation and they both work fine. If you are still having issues, please share with the Customer ID and Timestamp in UTC of a recent error. If you are using Postman, please also send me what you set in the “Headers” and “Body”.
