### ISSUE TITLE
Alexa isn't recognising ModeController utterances

### ISSUE THREAD

**Issue by madgeni** [alexa-samples/alexa-smarthome#105]
Ok, so I can discover devices with ModeController now - and they report back in the alexa site - 

remote 
Light/Switch 
Capability states: [ mode: Level.tv; TimeStamp: 2018-12-17T11:04:04.104Z; UncertaintyTime: 200; DeepQuery: True ]

But I can't interact with it - Alexa doesn't recognise my utterances, no matter how I try it. Am running on US account, using US servers.
Help?

**Comment by typasch** [comment]
Make sure that the device you're using is set to en-US as well. If you're using an echo, this is in settings.  If you're using the alexa mobile app, it takes it from the locale of the phone OS.

**Comment by madgeni** [comment]
Yep - so this could be the issue. the devices are set to en-US, and my code executes against the Virginia lambda, but i'm in the UK (but using alexa.amazon.com) - basically, i think my amazon a/c is forked, which is probably causing this.
So it works for you?

**Comment by madgeni** [comment]
Hi - is ModeController GA globally now?

**Comment by melchiorx** [comment]
Not yet, for a list of available marketplaces in SH APIs, check out https://developer.amazon.com/docs/device-apis/list-of-interfaces.html.

**Comment by aszk** [comment]
Closing because ModeController is available other than en-US now.
