### ISSUE TITLE
can't validate samples

### ISSUE THREAD

**Issue by doubledrat** [alexa-samples/alexa-smarthome#107]
so I've followed the instructions to use https://www.jsonschemavalidator.net/ but the sample responses are not validating, so I've no hope of validating my own code.

have I done something wrong?  I get 192 errors on the sample discovery response which starts

`{
    "event": {
        "header": {
            "namespace": "Alexa.Discovery",
            "name": "Discover.Response",
            "payloadVersion": "3",
            "messageId": "0a58ace0-e6ab-47de-b6af-b600b5ab8a7a"
        },
        "payload": {
            "endpoints": [
                {
                    "endpointId": "endpoint-001",
                    "manufacturerName": "Sample Manufacturer",
                    "friendlyName": "Switch",
                    "description": "001 Switch that can only be turned on/off",
                    "displayCategories": [`

**Comment by typasch** [comment]
The updated schema is actually working correctly.  The sample discovery response is wrong.  SceneController does not support a "proactivelyReported" property.  If you remove lines 467 and 505 (and the preceding commas) the example is valid.

**Comment by helviojr** [comment]
So, this issue should be closed, right?

**Comment by aszk** [comment]
Closing.
