### ISSUE TITLE
Channell controller not parsing channel string properly

### ISSUE THREAD

**Issue by kakarlavinodkumar** [alexa-samples/alexa-smarthome#109]
when i am saying channels like "star movies" (having spaces in channel name) are not parsed correctly
below is the payload when i asked alexa to "change channel to star movies on siti(device)".
Actually it should take "star movies" in name in channel metadata.but instead it is taking some other string

{
    "header": {
        "namespace": "Alexa.ChannelController",
        "name": "ChangeChannel",
        "payloadVersion": "3",
        "messageId": "c4f6da05-9e1b-4113-9627-8e593f1cf8db",
        "correlationToken": "AAAAAAAAAQBVXXV603XkwY9qyCMb48SSDAIAAAAAAAAAWLVcJj7xI9meAV+6OjeD4AZnFsuBh7ISUVSkatVMtIOgxxx3MzkrrvhqCuBXVKr9LBriOf4PGMmW1kqE31PYY25ljIUdutvNbFu/+CvlRMN/wOZF2W1Y31XPcZ92UgPoeA+fq9lvdVKnD03Erb9LKPXMGrR4UjYDaLlxGYApBC5PZWp/oAbXAtW6dq5P3McUu1IvW36CQl0hmrBMGbpO09Db3wylZseF/0uETdKeHmsl9W+o9VBNHxOabCn43uov1hCe/rJ+gqulfg9qkkxnm/3431LfM4RZDhR2sNXW2DNxB5bX2pCVxps2b+yczZgwLFnMwfYwLP8C3dTVVt9wBV2+HCu9t0ZQvH7V1sNl4ZtUaJAuDhPBzLjSPfkJbsyOPTst5dAYKxXaN33U2DnTj3XUP8RVm4ITbB/K28QPMEUQXZ6IA768qydLNHcZrTr2Ncv7h80bZcW8Y1Wo7zXFCWuOPi+jBtIMdRFfMNpvlZdH7zaOukF8Anp0V7vItpmlmKPipJZyJJrI9D7ZKMShBtN7t59eYXYjifcWBB1CkMOI6E6Q0L2mfC7b2aWXGmJvbq6RXc1zh/ef+mwH0lgaXHlp45kO7Ce2BHhxnivFPdRNicjKX0mLQnLewI1y6KYuY4GMmnvU4bDI00oHOpd4+PZ+3XkJlW8aDs8BoeNdtsKCYXn2Fe2JX7JT9Q=="
    },
    "endpoint": {
        "scope": {
            "type": "BearerToken",
            "token": "a098c4cd1a058e8d14444836294c17d83229b984"
        },
        "endpointId": "5be12d0ac5b80550cad2ec3f",
        "cookie": {
            "remote_codeset": "5acc47f9dd93b581afc4c8e9",
            "paired_ud": "5bfcf3f8b2cc696ac1900074",
            "kd_id": "807d3a5a3f37",
            "type": "irApp",
            "stb_provider_id": "2387"
        }
    },
    "payload": {
        "channel": {},
        **"channelMetadata": {
            "name": "Movies 24+"
        }**
    }
}

**Comment by AshokBaijal** [comment]
I am also facing similar problem. It looks like that the channel names are based on the US Channel names. It would have been better if the channel names are country specific depending on the locale where the Alexa device is registered. eg., "Sports" is returned as "AFN Sports", "News" becomes "News 18", "Entertainment" becomes "E! Entertainment", while India specific channels are not recognised at all.

**Comment by aszk** [comment]
This issue might come from ASR, NLU, or catalog issue. To investigate further, please https://alexa.design/contactus with activity key and discovery response.
