### ISSUE TITLE
Using your code to send commands to a smart device from a Raspberry Pi?

### ISSUE THREAD

**Issue by dimstamat** [alexa-samples/alexa-smarthome#114]
Hi,
I'm sorry for posting this as an issue but I couldn't find support in the forums. I saw your tutorial and it is very useful. However, my case is a little bit different. I need a way to trigger a smart plug connected to Alexa from a Raspberry Pi. I have found lots of resources and examples that create Lambda Functions and custom skills, but I am not sure whether all these are required in my case. I have a smart plug connected to Alexa and controlled by voice as normal. I want to be able to control the device from my raspberry Pi without requiring to be activated by voice. I already completed the Code-Based Linking (CBL) for Other Devices and Platforms from my Raspberry Pi as described here:

https://developer.amazon.com/docs/alexa-voice-service/code-based-linking-other-platforms.html

After successfully completing it, I am able to register and get an access token in order to communicate with my Echo Dot. What are the next steps to be able to control my smart plug from my Raspberry Pi? Do I need to create a Smart Home Skill and a Lambda function?

Many thanks in advance,

Dimos

**Comment by CHESFA** [comment]
Hello @dimstamat 

Could you solve your problem?

Regards form México

**Comment by aszk** [comment]
You can create a skill but it is not required. https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/smart-home-for-avs.html However AVS functions are limited to public. Please be aware that you might not have access to some of functionalities. This sample skill is not specific to AVS but you can grasp the idea.
