### ISSUE TITLE
ThermostatController capabilities doesn't have a configuration property?

### ISSUE THREAD

**Issue by Capstan** [alexa-samples/alexa-smarthome#117]
According to the example in https://developer.amazon.com/docs/device-apis/alexa-thermostatcontroller.html#discovery, the `ThermostatController.capabilities` block contains a `configuration` block. From my reading of the schema, the ThermostatController's capabilities doesn't allow a configuration block. Is this an oversight, or drift or am I reading it wrong?

**Comment by limic-amazon** [comment]
Changes have been made to the ThermostatController API since 2017, including the `supportsScheduling` field, but it doesn't look like those changes were reflected in the validation schema.

**Comment by aszk** [comment]
supportesScheduling is deprecated. Please use https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-thermostatcontroller-schedule.html.
