### ISSUE TITLE
Channel controller does not work

### ISSUE THREAD

**Issue by elfdie00475** [alexa-samples/alexa-smarthome#125]
Hi,

I  try to create the home skill on my TV device.
I follow the discovery response example to set the capabilities of my device, and I  test the skill with command "Alexa, change channel to 200 on device". Then, Alexa response me "Sorry, I don't know that".
I see the cloud log, it doesn't record any log. 

Have any one can help me to solve this problem?

Here is my capabilities: 
[catpabilities.txt](https://github.com/alexa/alexa-smarthome/files/3380492/catpabilities.txt)

Thanks~~

**Comment by aszk** [comment]
It seems that your discovery doesn't have required fields. Please check https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-channelcontroller.html#discover-response-example for a sample. You need to specify "endpointId", and "endpoint" should be "endpoints". I also noticed there are couple of unnecessary fields such as "userId", "thingName".
