### ISSUE TITLE
get device list from alexa

### ISSUE THREAD

**Issue by mduzgun** [alexa-samples/alexa-smarthome#129]
Hi. 
Using Alexa Smart Home, only virtual devices that I created are listed.
Pyhsical devices are not listed. 
I want to get all my connected smart device list from Alexa. 
For example, sengled light - kitchen etc. 
How to do this?

**Comment by pmodukuru** [comment]
Ping on this - I am also interested in this capability. How do I get all connected smart device list from Alexa and their states?

ex. Phillips hue motion sensor presence state, Hue light state, etc.

**Comment by StefanOltmann** [comment]
I think this repository is dead.

**Comment by aszk** [comment]
At this point, the feature is not supported. Please send feedback to https://alexa.uservoice.com/
