### ISSUE TITLE
Smart home has low pass rate of turning on multiple devices

### ISSUE THREAD

**Issue by ssoto2** [alexa-samples/alexa-smarthome#132]
Currently, have FireTV Cube and Echo. The smart home is connected with TP-Link Kasa App. In my office, there is 3 lights setup. One tp-link plug into a lamp (HS-105) and two tp-link bulbs (LB-130). Amazon Echo is very good turning on these 3 lights individually. When it comes to turning on all the light at once the echo is about 1 in 15. To make it more of a pain, often it will turn all the light on and immediately back off except for 1 of the 3. In the house, there is a google home hub and complete the same task always.

**Comment by aszk** [comment]
I'd recommend contacting https://www.amazon.com/gp/help/customer/display.html?nodeId=202009680 if you are a user of Kasa skill. If you are a developer of Kasa skill, please contact https://alexa.design/contactus with your skill ID, and activity keys.
1. Go to the "Review Voice History" section of your Amazon account: https://www.amazon.com/alexa-privacy/apd/rvh
2. Open your browser's web developer console:
    Firefox:
        Click: Tools > Browser Tools > Web Developer Tools
        Click the "Console" tab
    Chrome:
        Click: View > Developer > Developer Tools
        Click the "Console" tab
3. On the "Review Voice History" page, click to expand an interaction
4. Observe that the activity key for that interaction will be printed in the "Console" tab. It will look similar to the following: A1412N2U20AXFQ#1694546396232#A1Z88NGR2BK6A2#G0B16D0493720033
