### ISSUE TITLE
Alexa Tower Fan not working with RangeController

### ISSUE THREAD

**Issue by XenLabsNikhil** [alexa-samples/alexa-smarthome#134]
I have created a new device (Tower Fan) named "Bedroom Fan" & implemented lambda function as mentioned in documentations below - 
https://developer.amazon.com/docs/smarthome/steps-to-build-a-smart-home-skill.html
https://developer.amazon.com/docs/smarthome/connect-a-tower-fan-to-alexa.html
https://developer.amazon.com/docs/device-apis/alexa-rangecontroller.html

I am trying the voice command as 
```
"set the bedroom fan speed to 5"
"set the fan speed on the bedroom fan to maximum."
```

Now, these command are working well in Alexa Developer Console Test Section https://developer.amazon.com/alexa/console/ask
It is getting logged properly in CloudWatch.

But this same voice command is not working on alexa app as well as on Echo device. I always get the response as "I don't know how to set bedroom fan to that setting"
Nothing in the CloudWatch log.

I am using these devices from India.

What could be the reason?

**Comment by aszk** [comment]
If those work on the Alexa Developer Console and not on Alexa app, it might be an issue with natural language understanding or speech recognition. This is not specific to the repository. I'd recommend contacting https://alexa.design/contactus with activity keys.

1. Go to the "Review Voice History" section of your Amazon account: https://www.amazon.com/alexa-privacy/apd/rvh
2. Open your browser's web developer console:
    Firefox:
        Click: Tools > Browser Tools > Web Developer Tools
        Click the "Console" tab
    Chrome:
        Click: View > Developer > Developer Tools
        Click the "Console" tab
3. On the "Review Voice History" page, click to expand an interaction
4. Observe that the activity key for that interaction will be printed in the "Console" tab. It will look similar to the following: A1412N2U20AXFQ#1694546396232#A1Z88NGR2BK6A2#G0B16D0493720033
