### ISSUE TITLE
Alexa Certification Issue

### ISSUE THREAD

**Issue by rajenpal033** [alexa-samples/alexa-smarthome#140]
I have a set up for lambda function in EU(Ireland), I have provided ARN end points in skill for Default, and Europe, India text box, but when I submitted for certification, the issue given as follow:

> For Smart Home or Video interaction model functionality, you must have an active Lambda function in the supported language region. For example, if your skill supports UK users, you must have a Lambda function in the EU (Ireland) AWS region. More details can be found here. 

What should I do to fix this issue?

**Comment by aszk** [comment]
Does your skill supports other than languages that are associated to other region? 
https://developer.amazon.com/en-US/docs/alexa/smarthome/develop-smart-home-skills-in-multiple-languages.html#deploy

If you don't know how to add more endpoints, please refer https://developer.amazon.com/en-US/docs/alexa/smarthome/develop-smart-home-skills-in-multiple-languages.html for more details.
