### ISSUE TITLE
The guidance on how to get an utterance key for a particular phrase do not work.

### ISSUE THREAD

**Issue by SimonPhilpott** [alexa-samples/alexa-smarthome#143]
The URL provided navigates you to;

https://alexa.amazon.co.uk/spa/index.html?captcha_verified=1#cards

There is no way to select which device to show the responses from if you have more than one under the same account and opening the utterance details using the more dropdown does not give you a unique URL to send.

**Comment by maxgalbu** [comment]
I'm having the same issue

**Comment by aszk** [comment]
You can use https://alexa.amazon.co.uk/spa/index.html#settings/dialogs instead. You should be able to see device name in the line of utterance if the utterance came from device.
