### ISSUE TITLE
Alexa Skill ID showing null within SkillDebugger while testing in console.

### ISSUE THREAD

**Issue by matthewob5** [alexa-samples/alexa-smarthome#144]
After following the instructions in the tutorial, we were able to discover the virtual devices. However, when we tried to test the switch in the developer console, the skill debugger directive results in a null skillID as well as no further information about the state of the switch or context of the given command. Also, after looking at the Cloud Watch logs, it shows the discover directive but no directives for turning the switch on or off. Thanks!

**Comment by aszk** [comment]
This sounds like the utterance didn't go to your skill. Can you check if you have similar friendly name devices?
Please use https://alexa.design/contactus for further investigation with activity keys.
https://amazon.developer.forums.answerhub.com/articles/198661/how-do-i-get-an-utterance-activity-id-from-my-alex.html
