### ISSUE TITLE
Customizing Messaging

### ISSUE THREAD

**Issue by ThiagoA-Menezes** [alexa-samples/alexa-smarthome#147]
Hello All, 

I built my skill following this tutorial -> (https://github.com/alexa/alexa-smarthome/wiki/Build-a-Working-Smart-Home-Skill-in-15-Minutes) and I want to customize the commands like saying "Thunder" and the lights turns on, has anyone tried this before ?

**Comment by aszk** [comment]
We don't have a way to make custom voice command. You need to use pre-defined commands however SceneController might be close what you want to achieve. https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-scenecontroller.html
