### ISSUE TITLE
WakeOnLANController

### ISSUE THREAD

**Issue by Multiconecta** [alexa-samples/alexa-smarthome#155]
Current version does not support the new WakeOnLANController for Discovery Responses. Also for WakeUp event from Lambda to Alexa event gateway.

https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-wakeonlancontroller.html

**Comment by helviojr** [comment]
Created the Pull request for updating the validation schema for the new Alexa wake on LAN capability (#156 ).

**Comment by aszk** [comment]
WakeOnLAN has been added. Closing.
