### ISSUE TITLE
Emulated wemos devices unresponsive in alexa

### ISSUE THREAD

**Issue by apsathyan** [alexa-samples/alexa-smarthome#158]
Good day all, I am using 2 nos. wemos mini with 4 relays each for the past 2 years without any problem. Past 2 days the devices are unresponsive. I have deleted all the devices and discovered once again. But found 6 devices only out of eight and that too unresponsive. What should I do to use it as before.

**Comment by aszk** [comment]
Please use https://alexa.design/contactus if you still have the issue.
