### ISSUE TITLE
Adding my own development device esp8266 in alexa

### ISSUE THREAD

**Issue by naga-master** [alexa-samples/alexa-smarthome#162]
I have created my own smart home skill now i want to add my esp8266 into alexa app.how to make my esp8266 is discoverable by alexa.what are the credentials and code needed for arduino.any please help me to resolve this..

**Comment by yuriboeira11tx** [comment]
Same problem!

**Comment by aszk** [comment]
Please take a look 
- https://developer.amazon.com/en-US/docs/alexa/smarthome/understand-the-smart-home-skill-api.html
- https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-discovery.html#discover-response-example
- https://developer.amazon.com/en-US/docs/alexa/smarthome/discovery.html
for device discovery process. 

You need to send discovery responses for your device be discoverable from Alexa.
