### ISSUE TITLE
Add validation for Camera PTZ controllers

### ISSUE THREAD

**Issue by Logikz** [alexa-samples/alexa-smarthome#176]
There is a validation error for syntactically correct directive responses related to camera RTCSessionControllers
'Alexa.RTCSessionController' is not one of ['Alexa']

Failed validating 'enum' in schema[1]['properties']['event']['properties']['header']['properties']['namespace']:
    {'enum': ['Alexa'], 'type': 'string'}

On instance['event']['header']['namespace']:
    'Alexa.RTCSessionController'
----
Copied from example
{
  "event": {
    "header": {
      "namespace": "Alexa.RTCSessionController",
      "name": "SessionDisconnected",
      "messageId": "<message id>",
      "correlationToken": "<an opaque correlation token>",
      "payloadVersion": "3"
    },
    "endpoint": {
      "scope": {
        "type": "BearerToken",
        "token": "<an OAuth2 bearer token>"
      },
      "endpointId": "<endpoint id>"
    },
    "payload": {
      "sessionId" : "<the session identifier>"
    }
  }
}

**Comment by aszk** [comment]
We don't have a plan to add validation for SessionDisconnected at this point.
