### ISSUE TITLE
Getting Domain not whitelisted for using LWA javaScript SDK

### ISSUE THREAD

**Issue by bnisarg1** [alexa-samples/alexa-smarthome#177]
**we are getting allowed origin issue when trying to login with Amazon sdk using Alexa Client ID**

we know that in developer console websetting we can add allowed origin but its for **amazon client Id not alexa client ID**

**we need to add allowed origin for alexa client Id- How to do it?** The [link](https://forums.developer.amazon.com/questions/237595/how-to-had-allowed-origins-for-alexa-client-id.html) has error details.

**Comment by aszk** [comment]
Hello, Why do you need to add allowed origin for Alexa client id? I'd suggest checking https://developer.amazon.com/en-US/docs/alexa/smarthome/authenticate-a-customer-permissions.html document and if this doesn't help, please contact https://alexa.design/contactus.
