### ISSUE TITLE
Capability Evaluations & Test plans

### ISSUE THREAD

**Issue by supreetd21** [alexa-samples/alexa-smarthome#178]
The [automated smart home tests](https://developer.amazon.com/en-US/docs/alexa/smarthome/test-automated.html) provide an easy way to test the discovered devices, although it presently seems to support only a select few capabilities(Power, Brightness, Color & Thermostat).

Could you please shed some light on your plans to support all the Alexa smart home capabilities?
If possible, we are planning to use the test suite for testing several other devices and capabilities in the skill.

Also, would you be accepting PRs extending the support for the same?

**Comment by aszk** [comment]
Hello thank you for your questions.
> Could you please shed some light on your plans to support all the Alexa smart home capabilities?
We can't provide future plans.

> accepting PRs
We accept PRs if those are reasonable and meet our requirements.
