### ISSUE TITLE
Adding Alexa.Cooking interfaces into the Validation Schemas?

### ISSUE THREAD

**Issue by colinbashbash** [alexa-samples/alexa-smarthome#180]
It doesn't appear that the following schemas have been added. Is this something planned?
Alexa.Cooking.FoodTemperatureController
Alexa.Cooking.FoodTemperatureSensor
Alexa.Cooking.TemperatureController
Alexa.Cooking.TemperatureSensor

Also the "Configuration" doesn't have any specific validation under Alexa.Cooking interface. (It's left as just being an object)

**Comment by aszk** [comment]
Thank you for your feedback! We don't have a plan to update validation schema for Cooking at this point.
