### ISSUE TITLE
Documentation misses an important gotcha

### ISSUE THREAD

**Issue by ramanraja** [alexa-samples/alexa-smarthome#183]
The documentation in tutorials like 
[link](https://developer.amazon.com/en-US/alexa/devices/connected-devices/development-resources/smart-home-skills/smart-home-skill-tutorial/module-6), [link](https://github.com/alexa-samples/skill-sample-python-smarthome-switch/blob/master/instructions/README.md) and [link](https://github.com/alexa/alexa-smarthome/wiki/Build-a-Working-Smart-Home-Skill-in-15-Minutes)
completely miss an important point: They assume that the reader is located in North America, and ask them to create the lambda and the database in us-east1 region.
This has created lot of frustration for beginners outside North America: With the lambda created in the wrong region, the device discovery process always fails without any indication of what went wrong.
Please add a prominent link to the following URL at the beginning of these tutorials:
https://developer.amazon.com/en-US/docs/alexa/smarthome/develop-smart-home-skills-in-multiple-languages.html#deploy

**Comment by abhinavdakalia** [comment]
A new table has been added which lists the Alexa endpoint region and associated AWS Lambda region that you must use at this URL https://developer.amazon.com/en-US/docs/alexa/smarthome/develop-smart-home-skills-in-multiple-languages.html#deploy

**Comment by aszk** [comment]
Thank you for your feedback. Added locale information.
