### ISSUE TITLE
How to report bugs?

### ISSUE THREAD

**Issue by Aymkdn** [alexa-samples/alexa-smarthome#191]
I found a bug with Alexa, but I don't know how to report it to the developers to get a fix.

I called the Alexa support from the Alexa app, but the support team from this service is kind of useless…

**Comment by aszk** [comment]
Thank you for the question. If you are a developer that developed the skill, please use https://alexa.design/contactus. If you are a user, you might be able to find the skill developer's contact information from description of the skill, or Terms of Use of their skill page.
