### ISSUE TITLE
Examples and templates for Smart Home node.js are out of date

### ISSUE THREAD

**Issue by nathankopp** [alexa-samples/alexa-smarthome#32]
As of 1/2/2018, there are still quite a few examples in the documentation that refer to the old V2 message format, which isn't supported anymore.

Also, if the developer follows the instructions "On the Select blueprint page, type home in the filter box. Select the alexa-smart-home-skill-adapter." (found here https://developer.amazon.com/docs/smarthome/steps-to-build-a-smart-home-skill.html), the blueprint will use V2 and therefore will be incompatible with the smart home skill that uses V3.

Sure, the examples here are up-to-date, but they are for Python, but the documentation uses Node.js code.

This is quite annoying. It would be great if Amazon could assign someone to go through all of the documentation, examples, and templates, and bring them up to date to V3. Thanks!

**Comment by simchery** [comment]
I've updated the steps in the walk through (https://developer.amazon.com/docs/smarthome/steps-to-build-a-smart-home-skill.html) to accommodate changes in the AWS console. The code was, and is, updated to work with v3. Still working on getting the blueprint code updated.

**Comment by Lordkirin** [comment]
I have been following the https://developer.amazon.com/docs/smarthome/steps-to-build-a-smart-home-skill.html
But I don't see how to have it point to my website. I have created to urls:
www.mysite/api/alexa/handlediscovery
www.mysite/api/alexa/handlepowercontrol
Where do I put these in the example the code?
I don't know python, but looking through that code I don't see where I would put my urls.

I have tested my site oauth and urls using ask skill so I have the basic json files working.
When I try my lambda skill it gives me an error right after i click the accept in my oauth.
So figure it's the lambda function is my problem. I can see the oauth is accepted in my database to create the access_token.

Any help would be great thanks

**Comment by aszk** [comment]
If you are building Smart Home Skill, you need to use lambda endpoint instead of your website at this point. https://developer.amazon.com/en-US/docs/alexa/smarthome/steps-to-build-a-smart-home-skill.html#create-a-lambda-function
Skill endpoints are different than account linking URLs. https://developer.amazon.com/en-US/docs/alexa/account-linking/account-linking-for-sh-and-other.html
