### ISSUE TITLE
Setting thermostat mode not replying properly

### ISSUE THREAD

**Issue by umarovt** [alexa-samples/alexa-smarthome#36]
Hi,

when I respond to your service with answer below, Alexa says "Device is not responding". I have double checked my response with your documentation and it seems to be structured correctly. Please help.

{
    "context": {
        "properties": [
            {
                "namespace": "Alexa.ThermostatController",
                "name": "targetSetpoint",
                "value": {
                    "value": 21,
                    "scale": "CELSIUS"
                },
                "timeOfSample": "2018-01-19T15:50:39.070Z",
                "uncertaintyInMilliseconds": 500
            },
            {
                "namespace": "Alexa.ThermostaController",
                "name": "thermostatMode",
                "value": "AUTO",
                "timeOfSample": "2018-01-19T15:50:39.070Z",
                "uncertaintyInMilliseconds": 500
            }
        ]
    },
    "event": {
        "header": {
            "namespace": "Alexa",
            "name": "Response",
            "payloadVersion": "3",
            "messageId": "...",
            "correlationToken": "..."
        },
        "endpoint": {
            "endpointId": "..."
        },
        "payload": {}
    }
}

**Comment by p000** [comment]
Hello @umarovt 

I believe you are keying in the messageID, correlationToken, endpointID form the request to the response instead "..."

**Comment by aszk** [comment]
Do you still have this issue? If so, please feel free to https://alexa.design/contactus with your discovery response and full change report.
