### ISSUE TITLE
Need clarification on "scope" field

### ISSUE THREAD

**Issue by ralingam** [alexa-samples/alexa-smarthome#44]
@briankel  - is there any documentation on what the "scope" field under configuration tab ?
I am trying to follow the steps under "Build a Working Smart Home Skill in 15 Minutes"
![image](https://user-images.githubusercontent.com/36521067/36282828-49e57bc0-1257-11e8-9a4f-2e39e50dc465.png)

**Comment by mikemaas-amazon** [comment]
I can answer this one. It is the access scope and defines what customer data you need to access. A good overview can be found here: https://developer.amazon.com/docs/login-with-amazon/customer-profile.html
