### ISSUE TITLE
Sample Backend Docs

### ISSUE THREAD

**Issue by otoolema** [alexa-samples/alexa-smarthome#46]
When running through the docs on the Sample Backend, we see "KeyError:'friendlyName'" at step 6.2.2. After looking into things a bit more, it seems that changes have been pushed to api_handler_endpoint.py have changed the requirements for the POST body (https://github.com/alexa/alexa-smarthome/commit/835e2a767fa2767d492244b10f41fa284a324216#diff-a009b70fe12e911579b4ff26ef10fb10L194).

This also looks like it impacts the sample_backend.postman_collection.json. 

If this is not the cause of the error, what are the steps toward remediation? If this is the cause of the error, can we update the documentation?

Also related to: https://forums.developer.amazon.com/questions/112881/why-getting-keyerrorfriendlyname.html

**Comment by mikemaas-amazon** [comment]
Good catch, it is the sample postman collection that is the main culprit here. It was updated with samples to support the changes but was not updated. I will commit that change and make a pass through the documentation tonight to clear up some other things that have gone stale.
