### ISSUE TITLE
How to add new custom mode "DRY" to ThermostatController interface values like "COOL","AUTO",etc ?

### ISSUE THREAD

**Issue by abhishek-gajjar** [alexa-samples/alexa-smarthome#63]
I want to add new modes like "DRY" and "TURBO" to existing modes like ,"AUTO","COOL" and ,etc . 
Can you please suggest me that .

**Comment by dievaa** [comment]
The Alexa.ThermostatController interface only supports below modes at the moment:

- AUTO (Indicates automatic heating or cooling based on the current temperature and the setpoint)
- COOL (Indicates cooling mode)
- HEAT (Indicates heating mode)
- ECO (Indicates economy mode)
- OFF (Indicates that heating and cooling is off, but the device might still have power)

If you have custom modes, then better to use primitive controller like “Alexa.ModeController" where you can provide custom modes details in discovery response.

Check below link to know more about ModeController:
https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-modecontroller.html
