### ISSUE TITLE
deviceID

### ISSUE THREAD

**Issue by madgeni** [alexa-samples/alexa-smarthome#68]
Hi - 

as the Alexa Skills Kit now supports providing the echo deviceID in the request payload - can we get this for the Smart Home API also?

Thanks

**Comment by aszk** [comment]
No, there is no way to get deviceId with Smart Home skill at this point. However if you use [MCS](https://developer.amazon.com/en-US/docs/alexa/smarthome/about-mcs.html)(Muti-Capability Skill), you can receive intent requests like Custom Skill. Although this still doesn't include deviceId in the Smart Home payload. A user intentionally asks your skill to do something to receive intent requests, like using custom skills.
