### ISSUE TITLE
Issue in Account Linking

### ISSUE THREAD

**Issue by ParikshitSinghTomar** [alexa-samples/alexa-smarthome#71]
Same account linking controller working perfect for custom skill but when I tried this controller for smart home skill its not working. I read each and every step in "Link a alexa user" guide and don't find any different process for custom and smart home skills. I am following auth2.0 (Authorization Grant Flow).

**Comment by sw-devendra** [comment]
I am facing the same issue. I followed the steps line by line, used LWA for authentication, but unable to link the account. I tried on many browsers and devices, but got no success.

**Comment by aszk** [comment]
This Issues is for alexa-samrthome. If you are having account linking issue, please feel free to contact us. https://alexa.design/contactus
