### ISSUE TITLE
An error occurred while attempting to link your account with the skill. Please try again later.

### ISSUE THREAD

**Issue by faheemmuhammed17** [alexa-samples/alexa-smarthome#72]

**Comment by dievaa** [comment]
Do you still have the issue? If so, as starting point, I would strongly recommend reading over the following blog and knowledge base articles. They cover the most common points of friction that Alexa developers encounter with account linking, as well as providing some tips on how to best debug your skill's account linking implementation:

Account linking debugging knowledge base article: https://amazon.developer.forums.answerhub.com/articles/38610/alexa-debugging-account-linking.html
Troubleshooting account linking blog: https://developer.amazon.com/en-US/blogs/alexa/alexa-skills-kit/2020/12/troubleshooting-common-account-linking-issues-with-alexa-skills
App-to-App account linking debugging: https://amazon.developer.forums.answerhub.com/articles/240817/app-to-app-account-linking-debugging-tips.html

If the suggestions above didn't resolve the issue, please do not hesitate to reach out to us via the [Contact Us](https://developer.amazon.com/alexa/console/contact-us) page providing the Customer ID and Timestamp in UTC of a recent error.
