### ISSUE TITLE
Does Alexa support MJPEG video code format?

### ISSUE THREAD

**Issue by hiteshkpatel** [alexa-samples/alexa-smarthome#79]
Hi, 

I tested my camera H264 stream using Alexa. But it is not working with MJPEG stream. So I am not sure Alexa support MJPEG stream or not ? As per document it supports H264 video but when I 
 see the link https://developer.amazon.com/de/docs/device-apis/alexa-camerastreamcontroller.html and it describes that cameraStream.videoCodec can H264", "MPEG2", "MJPEG", or "JPG". So it is confusing.

Thank you in advance ...!!

Regards,
Hitesh

**Comment by aszk** [comment]
That is supported. Please use https://alexa.design/contactus if you are still having an issue to play your stream.
