### ISSUE TITLE
Same body error response, different Alexa responses

### ISSUE THREAD

**Issue by OlimpiaMM** [alexa-samples/alexa-smarthome#87]
I am making a SetThermostatMode command but in my logic this is not possible, so I've created an error body response with the namespace: Alexa.ThermostatController.
I have this two examples for this command:

Alexa, set the thermostat to heat -> I'm not quite sure what went wrong - The wrong message.
Alexa, set the thermostat name to heat -> That command doesn't work on device - The correct message.

Why is my response body handled differently?

**Comment by aszk** [comment]
We need to get activity keys for further investigation. Please use https://alexa.design/contactus along with activity keys.
https://github.com/alexa-samples/alexa-smarthome/wiki/How-To-Get-Utterance-Activity-Keys
