### ISSUE TITLE
How to get user's email and connect to device cloud server

### ISSUE THREAD

**Issue by abhitheawesomecoder** [alexa-samples/alexa-smarthome#97]
To find users specific device during discovery I need users email, so, how can I find that. 

I can't find any examples of connection between lambda and device cloud server and communication between them.

**Comment by thangta** [comment]
Hi, are you resolve it?

**Comment by aszk** [comment]
There is no way to retrieve user's email address with Smart Home Skill Type. Usually retrieving email address is not necessary for SH skills. Your cloud and Alexa has to be linked with [account linking](https://developer.amazon.com/en-US/docs/alexa/account-linking/account-linking-for-sh-and-other.html). However it is possible if your skill is [Multi-capability Skill](https://developer.amazon.com/en-US/docs/alexa/smarthome/about-mcs.html). You can use https://developer.amazon.com/en-US/docs/alexa/custom-skills/request-customer-contact-information-for-use-in-your-skill.html to retrieve user's email address.
